name: Performance Benchmarking

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sundays

jobs:
  benchmark:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install mlx>=0.15
        python -m pip install -e .
        python -m pip install pytest numpy pandas

    - name: Compile Metal Kernel (macOS only)
      if: matrix.os == 'macos-latest'
      run: |
        set -e
        cd mlx_audio/codec/models/encodec
        xcrun metal -c -std=macos-metal2.3 LSTM.metal -o LSTM.air
        xcrun metallib LSTM.air -o LSTM.metallib
        rm LSTM.air
        cd ../../../..

    - name: Run benchmarks
      run: |
        cd mlx_audio/codec/tests
        pytest test_encodec.py -k "benchmark" -v --benchmark-json=benchmark_results.json
        
    - name: Upload benchmark results
      uses: actions/upload-artifact@v3
      with:
        name: benchmark-results-${{ matrix.os }}
        path: mlx_audio/codec/tests/benchmark_results.json
