name: Numerical Validation

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  numerical-tests:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version: ['3.10']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install mlx>=0.15
        python -m pip install -e .
        python -m pip install pytest numpy

    - name: Compile Metal Kernel (macOS only)
      if: matrix.os == 'macos-latest'
      run: |
        set -e
        cd mlx_audio/codec/models/encodec
        xcrun metal -c -std=macos-metal2.3 LSTM.metal -o LSTM.air
        xcrun metallib LSTM.air -o LSTM.metallib
        rm LSTM.air
        cd ../../../..

    - name: Run numerical tests
      run: |
        cd mlx_audio/codec/tests
        pytest test_encodec.py -k "numerical" -v
