name: Windows ARM Validation

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  windows-arm:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install ONNX Runtime
      run: |
        python -m pip install onnxruntime-directml

    - name: Install dependencies
      run: |
        python -m pip install -e .
        python -m pip install pytest numpy

    - name: Run Windows ARM validation tests
      run: |
        cd mlx_audio/codec/tests
        pytest test_encodec.py -k "windows_arm" -v
